services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /data/config/sabnzbd/config:/config
      - /mnt/data/usenet:/data/usenet
    ports:
      - 8181:8080
    dns:
      - 8.8.8.8
      - 1.1.1.1
    restart: unless-stopped
