#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const yaml = require("yaml");

const root = path.resolve(__dirname, "..");
const registryPath = path.join(root, "services", "routes.yaml");
const inventoryPath = path.join(root, "ansible", "inventories", "generated", "hosts.yaml");
const caddyfilePath = path.join(root, "stacks", "rp", "Caddyfile");
const routesDocPath = path.join(root, "docs", "routes.md");
const natRulesPath = path.join(root, "docs", "proxmox-lan-dnat-rules.v4");

function readYaml(filePath) {
  return yaml.parse(fs.readFileSync(filePath, "utf8"));
}

function loadInventoryHosts() {
  const inventory = readYaml(inventoryPath);
  return Object.fromEntries(
    Object.entries(inventory.all.hosts).map(([name, data]) => [name, data.ansible_host]),
  );
}

function resolveUpstream(service, inventoryHosts) {
  if (service.upstream) return service.upstream;

  const host = service.upstream_host;
  if (!inventoryHosts[host]) {
    throw new Error(`${service.name}: unknown upstream_host ${host}`);
  }

  const scheme = service.upstream_scheme || "http";
  return `${scheme}://${inventoryHosts[host]}:${service.upstream_port}`;
}

function caddyBlock(hosts, service, upstream) {
  const caddy = service.caddy || {};
  const hasOptions = caddy.tls_insecure_skip_verify || caddy.flush_interval || (caddy.headers || []).length;

  if (!hasOptions) {
    return [`${hosts.join(", ")} {`, `\treverse_proxy ${upstream}`, "}"].join("\n");
  }

  const lines = [`${hosts.join(", ")} {`, `\treverse_proxy ${upstream} {`];

  if (caddy.tls_insecure_skip_verify) {
    lines.push("\t\ttransport http {");
    lines.push("\t\t\ttls_insecure_skip_verify");
    lines.push("\t\t}");
  }

  if (caddy.flush_interval) {
    lines.push(`\t\tflush_interval ${caddy.flush_interval}`);
  }

  for (const header of caddy.headers || []) {
    lines.push(`\t\t${header}`);
  }

  lines.push("\t}");
  lines.push("}");
  return lines.join("\n");
}

function joinBlocks(blocks) {
  return blocks.flatMap((block, index) => {
    const lines = block.split("\n");
    return index === 0 ? lines : ["", ...lines];
  });
}

function renderCaddy(registry, inventoryHosts) {
  const publicBlocks = [];
  const internalBlocks = [];

  for (const service of registry.services) {
    const publicHosts = service.public_hosts || [];
    let internalHosts = service.internal_hosts || [];
    const upstream = resolveUpstream(service, inventoryHosts);

    if (publicHosts.length) {
      const combinedHosts = [
        ...publicHosts,
        ...internalHosts.filter(
          (host) => service.external && service.name === "jellyfin",
        ),
      ];
      publicBlocks.push(caddyBlock(combinedHosts, service, upstream));

      if (service.external && service.name === "jellyfin") {
        internalHosts = [];
      }
    }

    if (internalHosts.length) {
      internalBlocks.push(caddyBlock(internalHosts, service, upstream));
    }
  }

  return [
    "{",
    `\tacme_dns ${registry.caddy.acme_dns}`,
    "",
    "\t# Prefer the broadly trusted RSA-rooted chain for older LAN clients.",
    "\tpreferred_chains {",
    '\t\troot_common_name "ISRG Root X1"',
    "\t}",
    "}",
    "",
    "# GENERATED by scripts/gen-routes.js from services/routes.yaml.",
    "# Do not edit by hand; update the registry and regenerate.",
    "",
    "# home.example - split-horizon public names also served locally",
    ...joinBlocks(publicBlocks),
    "",
    "# internal.home.example - LAN-only names",
    ...joinBlocks(internalBlocks),
    "",
  ].join("\n");
}

function upstreamLabel(service, upstream) {
  if (service.upstream_host) {
    return `${service.upstream_host}:${service.upstream_port} (${upstream})`;
  }
  return upstream;
}

function renderRoutesDoc(registry, inventoryHosts) {
  const rows = registry.services.map((service) => {
    const publicHosts = (service.public_hosts || []).map((host) => `\`${host}\``).join(", ") || "-";
    const internalHosts = (service.internal_hosts || []).map((host) => `\`${host}\``).join(", ") || "-";
    const external = service.external ? "yes" : "no";
    const upstream = resolveUpstream(service, inventoryHosts);
    return `| \`${service.name}\` | ${publicHosts} | ${internalHosts} | \`${upstreamLabel(service, upstream)}\` | ${external} |`;
  });

  const dnsRows = [...registry.dns.carveouts, ...registry.dns.wildcards].map(
    (item) => `| \`${item.domain}\` | \`${item.answer}\` | ${item.note} |`,
  );

  return [
    "# routes",
    "",
    "Generated from `services/routes.yaml` and Ansible inventory by `scripts/gen-routes.js`.",
    "",
    "## caddy routes",
    "",
    "| Service | Public hosts | Internal hosts | Upstream | External |",
    "|---|---|---|---|---|",
    ...rows,
    "",
    "## split DNS",
    "",
    `Router DHCP DNS should point clients at \`${registry.dns.lan_dns}\`.`,
    `Tailscale split DNS for \`internal.home.example\` should point at \`${registry.dns.tailscale_dns}\`.`,
    "",
    "| Domain | Answer | Note |",
    "|---|---|---|",
    ...dnsRows,
    "",
  ].join("\n");
}

function targetIp(target, inventoryHosts) {
  if (target.ip) return target.ip;
  if (!inventoryHosts[target.host]) {
    throw new Error(`unknown NAT target host ${target.host}`);
  }
  return inventoryHosts[target.host];
}

function renderNatRules(registry, inventoryHosts) {
  const entrypoints = registry.entrypoints;
  const internal = entrypoints.internal;
  const dnsIp = targetIp(internal.dns_target, inventoryHosts);
  const webIp = targetIp(internal.web_target, inventoryHosts);
  const rules = [];
  const forwardRules = [];

  for (const entrypointName of ["proxmox_lan", "proxmox_tailscale"]) {
    const entrypoint = entrypoints[entrypointName];
    const iface = entrypoint.interface;

    if (entrypoint.forward_dns) {
      rules.push(`-A PREROUTING -i ${iface} -p udp -m udp --dport 53 -j DNAT --to-destination ${dnsIp}:${internal.dns_target.udp_port}`);
      rules.push(`-A PREROUTING -i ${iface} -p tcp -m tcp --dport 53 -j DNAT --to-destination ${dnsIp}:${internal.dns_target.tcp_port}`);

      forwardRules.push(`-A FORWARD -i ${iface} -o vmbr0 -p udp -d ${dnsIp} -m udp --dport ${internal.dns_target.udp_port} -j ACCEPT`);
      forwardRules.push(`-A FORWARD -i ${iface} -o vmbr0 -p tcp -d ${dnsIp} -m tcp --dport ${internal.dns_target.tcp_port} -j ACCEPT`);
    }

    if (entrypoint.forward_web) {
      for (const port of internal.web_target.tcp_ports || []) {
        rules.push(`-A PREROUTING -i ${iface} -p tcp -m tcp --dport ${port} -j DNAT --to-destination ${webIp}:${port}`);
      }

      for (const port of internal.web_target.udp_ports || []) {
        rules.push(`-A PREROUTING -i ${iface} -p udp -m udp --dport ${port} -j DNAT --to-destination ${webIp}:${port}`);
      }

      for (const port of internal.web_target.tcp_ports || []) {
        forwardRules.push(`-A FORWARD -i ${iface} -o vmbr0 -p tcp -d ${webIp} -m tcp --dport ${port} -j ACCEPT`);
      }

      for (const port of internal.web_target.udp_ports || []) {
        forwardRules.push(`-A FORWARD -i ${iface} -o vmbr0 -p udp -d ${webIp} -m udp --dport ${port} -j ACCEPT`);
      }
    }
  }

  return [
    "# Static IPv4 rules for Proxmox LAN and Tailscale homelab entrypoints.",
    "# GENERATED by scripts/gen-routes.js from services/routes.yaml.",
    "# Ansible installs this as /etc/iptables/rules.v4 for reboot persistence.",
    "# Do not reload this live with netfilter-persistent while Tailscale is running;",
    "# the proxmox_network role applies live rules idempotently with iptables.",
    "#",
    "# LAN clients use 192.0.2.10. Tailscale clients use 100.64.0.10.",
    "# LAN DNS terminates on dnsmasq at 192.0.2.10 and is forwarded to Pi-hole.",
    "*nat",
    ":PREROUTING ACCEPT [0:0]",
    ":INPUT ACCEPT [0:0]",
    ":OUTPUT ACCEPT [0:0]",
    ":POSTROUTING ACCEPT [0:0]",
    ...rules,
    "-A POSTROUTING -s 10.20.0.0/24 -o eth0 -j MASQUERADE",
    "COMMIT",
    "",
    "*raw",
    ":PREROUTING ACCEPT [0:0]",
    ":OUTPUT ACCEPT [0:0]",
    "COMMIT",
    "",
    "*filter",
    ":INPUT ACCEPT [0:0]",
    ":FORWARD ACCEPT [0:0]",
    ":OUTPUT ACCEPT [0:0]",
    ...forwardRules,
    "-A FORWARD -i eth0 -o vmbr0 -m state --state RELATED,ESTABLISHED -j ACCEPT",
    "-A FORWARD -i tailscale0 -o vmbr0 -m state --state RELATED,ESTABLISHED -j ACCEPT",
    "-A FORWARD -i vmbr0 -o eth0 -j ACCEPT",
    "-A FORWARD -i vmbr0 -o tailscale0 -j ACCEPT",
    "COMMIT",
    "",
  ].join("\n");
}

function writeOrCheck(filePath, content, check) {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null;
  if (check) {
    return current === content;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content, "utf8");
  return true;
}

function main() {
  const check = process.argv.includes("--check");
  const registry = readYaml(registryPath);
  const inventoryHosts = loadInventoryHosts();
  const outputs = [
    [caddyfilePath, renderCaddy(registry, inventoryHosts)],
    [routesDocPath, renderRoutesDoc(registry, inventoryHosts)],
    [natRulesPath, renderNatRules(registry, inventoryHosts)],
  ];

  let ok = true;
  for (const [filePath, content] of outputs) {
    const fresh = writeOrCheck(filePath, content, check);
    if (check && !fresh) {
      console.log(`stale: ${path.relative(root, filePath)}`);
    }
    ok = ok && fresh;
  }

  if (check && !ok) {
    process.exit(1);
  }
}

main();
